
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.Frame fraLogo;
	private global::Gtk.Alignment GtkAlignment46;
	private global::Gtk.Image imgLogo;
	private global::Gtk.Notebook nbFrames;
	private global::Gtk.HBox hbHomeFrame;
	private global::Gtk.VBox vb_HomeFrameButtons;
	private global::Gtk.Frame fraHomeFrameButtons;
	private global::Gtk.Alignment GtkAlignment;
	private global::Gtk.VBox vbox3;
	private global::Gtk.Button btn_ViewDevices;
	private global::Gtk.Button btnViewServers;
	private global::Gtk.Alignment alignment1;
	private global::Gtk.VPaned vpaned11;
	private global::Gtk.Button btn_Quit;
	private global::Gtk.Frame fra_HomeFrame;
	private global::Gtk.Alignment GtkAlignment4;
	private global::Gtk.VPaned vpaned1;
	private global::Gtk.Image image505;
	private global::Gtk.Label lbl_nbHome;
	private global::Gtk.HBox hbConfigFrame;
	private global::Gtk.VBox vb_ConfigFrameButtons;
	private global::Gtk.Frame fraConfigFrameButtons;
	private global::Gtk.Alignment GtkAlignment5;
	private global::Gtk.VBox vbox4;
	private global::Gtk.Button btn_ConfigBack;
	private global::Gtk.Button btnConfigServers;
	private global::Gtk.Button btn_ManageDevices;
	private global::Gtk.Button btn_Installation;
	private global::Gtk.Alignment alignment2;
	private global::Gtk.VPaned vpaned10;
	private global::Gtk.Button btnConfigHome;
	private global::Gtk.Frame fra_ConfigFrame;
	private global::Gtk.Alignment GtkAlignment11;
	private global::Gtk.VPaned vpaned3;
	private global::Gtk.Image img_configBG;
	private global::Gtk.Label lbl_nbConfig;
	private global::Gtk.HBox bhServerSettings;
	private global::Gtk.Frame fraInstallationButtons;
	private global::Gtk.Alignment GtkAlignment29;
	private global::Gtk.VBox vbox5;
	private global::Gtk.Button btnServerSettingsBack;
	private global::Gtk.Button btnServerSettingsSave;
	private global::Gtk.VPaned vpaned4;
	private global::Gtk.Button btnServerSettingsHome;
	private global::Gtk.Frame frame2;
	private global::Gtk.Alignment GtkAlignment36;
	private global::Gtk.HBox hbox2;
	private global::Gtk.Frame fraSettings;
	private global::Gtk.Alignment GtkAlignment37;
	private global::Gtk.VBox vbox6;
	private global::Gtk.HBox hbox8;
	private global::Gtk.Label label12;
	private global::Gtk.Entry entFriendlyName;
	private global::Gtk.HBox hbox3;
	private global::Gtk.Label label3;
	private global::Gtk.ComboBoxEntry cboProtocol;
	private global::Gtk.Entry entPort;
	private global::Gtk.Label label4;
	private global::Gtk.HBox hbox4;
	private global::Gtk.Label label2;
	private global::Gtk.Entry entServer;
	private global::Gtk.HBox hbox5;
	private global::Gtk.Label label5;
	private global::Gtk.Entry entBaseDir;
	private global::Gtk.VBox vbox7;
	private global::Gtk.CheckButton cbAuth;
	private global::Gtk.Frame fraAuth;
	private global::Gtk.Alignment GtkAlignment41;
	private global::Gtk.VBox vbox8;
	private global::Gtk.HBox hbox6;
	private global::Gtk.Label label41;
	private global::Gtk.Entry entUname;
	private global::Gtk.HBox hbox7;
	private global::Gtk.Label label51;
	private global::Gtk.Entry entPword;
	private global::Gtk.Label GtkLabel29;
	private global::Gtk.VPaned vpaned5;
	private global::Gtk.Label lbl_nbServerSettings;
	private global::Gtk.HBox hbServerBrowser;
	private global::Gtk.Frame frame3;
	private global::Gtk.Alignment GtkAlignment19;
	private global::Gtk.VBox vbox9;
	private global::Gtk.Button btnServerBrowserBack;
	private global::Gtk.VPaned vpaned6;
	private global::Gtk.Button btnServerBrowserHome;
	private global::Gtk.HBox hbox13;
	private global::Gtk.Frame fraServerBrowser;
	private global::Gtk.Alignment GtkAlignment40;
	private global::Gtk.IconView ivServerBrowser;
	private global::Gtk.Label lbl_nbServerBrowser;
	private global::Gtk.HBox hbDeviceBrowser;
	private global::Gtk.Frame fraDeviceBrowserButtons;
	private global::Gtk.Alignment GtkAlignment34;
	private global::Gtk.VBox vbox10;
	private global::Gtk.Button btnDeviceBrowserBack;
	private global::Gtk.VPaned vpaned7;
	private global::Gtk.Button btnDeviceBrowserHome;
	private global::Gtk.HBox hbox10;
	private global::Gtk.Frame fraDeviceBrowser;
	private global::Gtk.Alignment GtkAlignment39;
	private global::Gtk.IconView ivDeviceBrowser;
	private global::Gtk.Label lbl_nbDeviceBrowser;
	private global::Gtk.HBox hbDeviceSettings;
	private global::Gtk.Frame frame4;
	private global::Gtk.Alignment GtkAlignment22;
	private global::Gtk.VBox vbox11;
	private global::Gtk.Button btnDeviceSettingsBack;
	private global::Gtk.Button btnDeviceSettingsSave;
	private global::Gtk.VPaned vpaned8;
	private global::Gtk.Button btnDeviceSettingsHome;
	private global::Gtk.VBox vbox12;
	private global::Gtk.Frame frame11;
	private global::Gtk.Alignment GtkAlignment26;
	private global::Gtk.VBox vbox13;
	private global::Gtk.HBox hbox15;
	private global::Gtk.Label label9;
	private global::Gtk.Entry entDeviceID;
	private global::Gtk.HBox hbox16;
	private global::Gtk.Label label10;
	private global::Gtk.Entry entDeviceDescription;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Label label11;
	private global::Gtk.Entry entDeviceLocation;
	private global::Gtk.Frame frame14;
	private global::Gtk.Alignment GtkAlignment27;
	private global::Gtk.VBox vbox14;
	private global::Gtk.HBox hbox17;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TreeView nvDeviceFileDescr;
	private global::Gtk.VBox vbox15;
	private global::Gtk.Button btnLogFileSensorUp;
	private global::Gtk.Button btnLogFileSensorDown;
	private global::Gtk.HBox hbox20;
	private global::Gtk.Button btnLogFileSensorAdd;
	private global::Gtk.Button btnLogFileSensorDelete;
	private global::Gtk.HPaned hpaned4;
	private global::Gtk.HPaned hpaned6;
	private global::Gtk.Button btnAddDefaultDescr;
	private global::Gtk.HPaned hpaned7;
	private global::Gtk.Label GtkLabel26;
	private global::Gtk.HBox hbox9;
	private global::Gtk.HBox hbox12;
	private global::Gtk.Label label14;
	private global::Gtk.Entry entDeviceServerSubDir;
	private global::Gtk.Button btnSettingsBrowse;
	private global::Gtk.HBox hbox11;
	private global::Gtk.Label label16;
	private global::Gtk.ComboBox cboDeviceServer;
	private global::Gtk.Label lbl_nbDeviceSettings;
	private global::Gtk.HBox hbGraph;
	private global::Gtk.Frame fraButtons;
	private global::Gtk.Alignment GtkAlignment35;
	private global::Gtk.VBox vbox17;
	private global::Gtk.VBox vbox19;
	private global::Gtk.Button btnGraphBack;
	private global::Gtk.VPaned vpaned9;
	private global::Gtk.Button btnGraphHome;
	private global::Gtk.Frame fraGraph;
	private global::Gtk.Alignment GtkAlignment42;
	private global::Gtk.HBox hbox23;
	private global::Gtk.VBox vbox2;
	private global::Gtk.Notebook nbGraph;
	private global::Gtk.ScrolledWindow swGraph;
	private global::Gtk.Label label1;
	private global::Gtk.ScrolledWindow swAlarms;
	private global::Gtk.TreeView tvwAlarms;
	private global::Gtk.Label label15;
	private global::Gtk.Label lblGraph;
	private global::Gtk.Label lbl_nbGraph;
	private global::Gtk.HBox hbFtpBrowser;
	private global::Gtk.Frame frame1;
	private global::Gtk.Alignment GtkAlignment43;
	private global::Gtk.VBox vbox16;
	private global::Gtk.Button btnFtpBack;
	private global::Gtk.VPaned vpaned12;
	private global::Gtk.Frame frame5;
	private global::Gtk.Alignment GtkAlignment45;
	private global::Gtk.IconView ivFtpBrowser;
	private global::Gtk.Label lbl_nbFtpBrowser;
	private global::Gtk.Statusbar sb_status;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("SubZeroViewer2");
		this.Icon = global::Gdk.Pixbuf.LoadFromResource ("SubZeroViewer2.res.icon.png");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		this.AllowGrow = false;
		this.Gravity = ((global::Gdk.Gravity)(2));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.fraLogo = new global::Gtk.Frame ();
		this.fraLogo.Name = "fraLogo";
		this.fraLogo.ShadowType = ((global::Gtk.ShadowType)(0));
		this.fraLogo.BorderWidth = ((uint)(5));
		// Container child fraLogo.Gtk.Container+ContainerChild
		this.GtkAlignment46 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment46.Name = "GtkAlignment46";
		this.GtkAlignment46.LeftPadding = ((uint)(12));
		// Container child GtkAlignment46.Gtk.Container+ContainerChild
		this.imgLogo = new global::Gtk.Image ();
		this.imgLogo.Name = "imgLogo";
		this.imgLogo.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("SubZeroViewer2.res.logo.png");
		this.GtkAlignment46.Add (this.imgLogo);
		this.fraLogo.Add (this.GtkAlignment46);
		this.vbox1.Add (this.fraLogo);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.fraLogo]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.nbFrames = new global::Gtk.Notebook ();
		this.nbFrames.CanFocus = true;
		this.nbFrames.Name = "nbFrames";
		this.nbFrames.CurrentPage = 1;
		this.nbFrames.ShowTabs = false;
		// Container child nbFrames.Gtk.Notebook+NotebookChild
		this.hbHomeFrame = new global::Gtk.HBox ();
		this.hbHomeFrame.Name = "hbHomeFrame";
		this.hbHomeFrame.Spacing = 6;
		this.hbHomeFrame.BorderWidth = ((uint)(3));
		// Container child hbHomeFrame.Gtk.Box+BoxChild
		this.vb_HomeFrameButtons = new global::Gtk.VBox ();
		this.vb_HomeFrameButtons.Name = "vb_HomeFrameButtons";
		this.vb_HomeFrameButtons.Spacing = 6;
		// Container child vb_HomeFrameButtons.Gtk.Box+BoxChild
		this.fraHomeFrameButtons = new global::Gtk.Frame ();
		this.fraHomeFrameButtons.Name = "fraHomeFrameButtons";
		this.fraHomeFrameButtons.ShadowType = ((global::Gtk.ShadowType)(4));
		this.fraHomeFrameButtons.BorderWidth = ((uint)(3));
		// Container child fraHomeFrameButtons.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		this.vbox3.BorderWidth = ((uint)(3));
		// Container child vbox3.Gtk.Box+BoxChild
		this.btn_ViewDevices = new global::Gtk.Button ();
		this.btn_ViewDevices.Name = "btn_ViewDevices";
		this.btn_ViewDevices.UseUnderline = true;
		this.btn_ViewDevices.FocusOnClick = false;
		this.btn_ViewDevices.Relief = ((global::Gtk.ReliefStyle)(2));
		global::Gtk.Image w4 = new global::Gtk.Image ();
		w4.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("SubZeroViewer2.res.buttons.view_installed_devices_blue.png");
		this.btn_ViewDevices.Image = w4;
		this.vbox3.Add (this.btn_ViewDevices);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.btn_ViewDevices]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.btnViewServers = new global::Gtk.Button ();
		this.btnViewServers.CanFocus = true;
		this.btnViewServers.Name = "btnViewServers";
		this.btnViewServers.UseUnderline = true;
		this.btnViewServers.FocusOnClick = false;
		this.btnViewServers.Relief = ((global::Gtk.ReliefStyle)(2));
		global::Gtk.Image w6 = new global::Gtk.Image ();
		w6.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("SubZeroViewer2.res.buttons.view_servers.png");
		this.btnViewServers.Image = w6;
		this.vbox3.Add (this.btnViewServers);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.btnViewServers]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment1.Name = "alignment1";
		// Container child alignment1.Gtk.Container+ContainerChild
		this.vpaned11 = new global::Gtk.VPaned ();
		this.vpaned11.CanFocus = true;
		this.vpaned11.Name = "vpaned11";
		this.vpaned11.Position = 1;
		this.alignment1.Add (this.vpaned11);
		this.vbox3.Add (this.alignment1);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.alignment1]));
		w9.Position = 2;
		// Container child vbox3.Gtk.Box+BoxChild
		this.btn_Quit = new global::Gtk.Button ();
		this.btn_Quit.Name = "btn_Quit";
		this.btn_Quit.UseUnderline = true;
		this.btn_Quit.FocusOnClick = false;
		this.btn_Quit.Relief = ((global::Gtk.ReliefStyle)(2));
		global::Gtk.Image w10 = new global::Gtk.Image ();
		w10.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("SubZeroViewer2.res.buttons.quit_blue.png");
		this.btn_Quit.Image = w10;
		this.vbox3.Add (this.btn_Quit);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.btn_Quit]));
		w11.PackType = ((global::Gtk.PackType)(1));
		w11.Position = 3;
		w11.Expand = false;
		w11.Fill = false;
		this.GtkAlignment.Add (this.vbox3);
		this.fraHomeFrameButtons.Add (this.GtkAlignment);
		this.vb_HomeFrameButtons.Add (this.fraHomeFrameButtons);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vb_HomeFrameButtons [this.fraHomeFrameButtons]));
		w14.Position = 0;
		this.hbHomeFrame.Add (this.vb_HomeFrameButtons);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbHomeFrame [this.vb_HomeFrameButtons]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		// Container child hbHomeFrame.Gtk.Box+BoxChild
		this.fra_HomeFrame = new global::Gtk.Frame ();
		this.fra_HomeFrame.Name = "fra_HomeFrame";
		this.fra_HomeFrame.BorderWidth = ((uint)(3));
		// Container child fra_HomeFrame.Gtk.Container+ContainerChild
		this.GtkAlignment4 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment4.Name = "GtkAlignment4";
		// Container child GtkAlignment4.Gtk.Container+ContainerChild
		this.vpaned1 = new global::Gtk.VPaned ();
		this.vpaned1.CanFocus = true;
		this.vpaned1.Name = "vpaned1";
		this.vpaned1.Position = 10;
		// Container child vpaned1.Gtk.Paned+PanedChild
		this.image505 = new global::Gtk.Image ();
		this.image505.Name = "image505";
		this.image505.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("SubZeroViewer2.res.codebg1.png");
		this.vpaned1.Add (this.image505);
		this.GtkAlignment4.Add (this.vpaned1);
		this.fra_HomeFrame.Add (this.GtkAlignment4);
		this.hbHomeFrame.Add (this.fra_HomeFrame);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbHomeFrame [this.fra_HomeFrame]));
		w19.Position = 1;
		this.nbFrames.Add (this.hbHomeFrame);
		// Notebook tab
		this.lbl_nbHome = new global::Gtk.Label ();
		this.lbl_nbHome.Name = "lbl_nbHome";
		this.lbl_nbHome.LabelProp = global::Mono.Unix.Catalog.GetString ("Home");
		this.nbFrames.SetTabLabel (this.hbHomeFrame, this.lbl_nbHome);
		this.lbl_nbHome.ShowAll ();
		// Container child nbFrames.Gtk.Notebook+NotebookChild
		this.hbConfigFrame = new global::Gtk.HBox ();
		this.hbConfigFrame.Name = "hbConfigFrame";
		this.hbConfigFrame.Spacing = 6;
		this.hbConfigFrame.BorderWidth = ((uint)(3));
		// Container child hbConfigFrame.Gtk.Box+BoxChild
		this.vb_ConfigFrameButtons = new global::Gtk.VBox ();
		this.vb_ConfigFrameButtons.Name = "vb_ConfigFrameButtons";
		this.vb_ConfigFrameButtons.Spacing = 6;
		// Container child vb_ConfigFrameButtons.Gtk.Box+BoxChild
		this.fraConfigFrameButtons = new global::Gtk.Frame ();
		this.fraConfigFrameButtons.Name = "fraConfigFrameButtons";
		this.fraConfigFrameButtons.ShadowType = ((global::Gtk.ShadowType)(4));
		this.fraConfigFrameButtons.BorderWidth = ((uint)(3));
		// Container child fraConfigFrameButtons.Gtk.Container+ContainerChild
		this.GtkAlignment5 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment5.Name = "GtkAlignment5";
		// Container child GtkAlignment5.Gtk.Container+ContainerChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		this.vbox4.BorderWidth = ((uint)(3));
		// Container child vbox4.Gtk.Box+BoxChild
		this.btn_ConfigBack = new global::Gtk.Button ();
		this.btn_ConfigBack.Name = "btn_ConfigBack";
		this.btn_ConfigBack.UseUnderline = true;
		this.btn_ConfigBack.FocusOnClick = false;
		this.btn_ConfigBack.Relief = ((global::Gtk.ReliefStyle)(2));
		global::Gtk.Image w21 = new global::Gtk.Image ();
		w21.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("SubZeroViewer2.res.buttons.back_blue.png");
		this.btn_ConfigBack.Image = w21;
		this.vbox4.Add (this.btn_ConfigBack);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.btn_ConfigBack]));
		w22.Position = 0;
		w22.Expand = false;
		w22.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.btnConfigServers = new global::Gtk.Button ();
		this.btnConfigServers.CanFocus = true;
		this.btnConfigServers.Name = "btnConfigServers";
		this.btnConfigServers.UseUnderline = true;
		this.btnConfigServers.Relief = ((global::Gtk.ReliefStyle)(2));
		global::Gtk.Image w23 = new global::Gtk.Image ();
		w23.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("SubZeroViewer2.res.buttons.servers_blue.png");
		this.btnConfigServers.Image = w23;
		this.vbox4.Add (this.btnConfigServers);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.btnConfigServers]));
		w24.Position = 1;
		w24.Expand = false;
		w24.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.btn_ManageDevices = new global::Gtk.Button ();
		this.btn_ManageDevices.Name = "btn_ManageDevices";
		this.btn_ManageDevices.UseUnderline = true;
		this.btn_ManageDevices.FocusOnClick = false;
		this.btn_ManageDevices.Relief = ((global::Gtk.ReliefStyle)(2));
		global::Gtk.Image w25 = new global::Gtk.Image ();
		w25.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("SubZeroViewer2.res.buttons.manage_installed_devices_blue.png");
		this.btn_ManageDevices.Image = w25;
		this.vbox4.Add (this.btn_ManageDevices);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.btn_ManageDevices]));
		w26.Position = 2;
		w26.Expand = false;
		w26.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.btn_Installation = new global::Gtk.Button ();
		this.btn_Installation.Name = "btn_Installation";
		this.btn_Installation.UseUnderline = true;
		this.btn_Installation.FocusOnClick = false;
		this.btn_Installation.Relief = ((global::Gtk.ReliefStyle)(2));
		global::Gtk.Image w27 = new global::Gtk.Image ();
		w27.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("SubZeroViewer2.res.buttons.manage_installation_blue.png");
		this.btn_Installation.Image = w27;
		this.vbox4.Add (this.btn_Installation);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.btn_Installation]));
		w28.Position = 3;
		w28.Expand = false;
		w28.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.alignment2 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment2.Name = "alignment2";
		// Container child alignment2.Gtk.Container+ContainerChild
		this.vpaned10 = new global::Gtk.VPaned ();
		this.vpaned10.CanFocus = true;
		this.vpaned10.Name = "vpaned10";
		this.vpaned10.Position = 1;
		this.alignment2.Add (this.vpaned10);
		this.vbox4.Add (this.alignment2);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.alignment2]));
		w30.Position = 4;
		// Container child vbox4.Gtk.Box+BoxChild
		this.btnConfigHome = new global::Gtk.Button ();
		this.btnConfigHome.CanFocus = true;
		this.btnConfigHome.Name = "btnConfigHome";
		this.btnConfigHome.UseUnderline = true;
		this.btnConfigHome.Relief = ((global::Gtk.ReliefStyle)(2));
		global::Gtk.Image w31 = new global::Gtk.Image ();
		w31.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("SubZeroViewer2.res.buttons.home_blue.png");
		this.btnConfigHome.Image = w31;
		this.vbox4.Add (this.btnConfigHome);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.btnConfigHome]));
		w32.PackType = ((global::Gtk.PackType)(1));
		w32.Position = 6;
		w32.Expand = false;
		w32.Fill = false;
		this.GtkAlignment5.Add (this.vbox4);
		this.fraConfigFrameButtons.Add (this.GtkAlignment5);
		this.vb_ConfigFrameButtons.Add (this.fraConfigFrameButtons);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vb_ConfigFrameButtons [this.fraConfigFrameButtons]));
		w35.Position = 0;
		this.hbConfigFrame.Add (this.vb_ConfigFrameButtons);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbConfigFrame [this.vb_ConfigFrameButtons]));
		w36.Position = 0;
		w36.Expand = false;
		w36.Fill = false;
		// Container child hbConfigFrame.Gtk.Box+BoxChild
		this.fra_ConfigFrame = new global::Gtk.Frame ();
		this.fra_ConfigFrame.Name = "fra_ConfigFrame";
		this.fra_ConfigFrame.ShadowType = ((global::Gtk.ShadowType)(4));
		this.fra_ConfigFrame.BorderWidth = ((uint)(3));
		// Container child fra_ConfigFrame.Gtk.Container+ContainerChild
		this.GtkAlignment11 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment11.Name = "GtkAlignment11";
		this.GtkAlignment11.LeftPadding = ((uint)(12));
		// Container child GtkAlignment11.Gtk.Container+ContainerChild
		this.vpaned3 = new global::Gtk.VPaned ();
		this.vpaned3.CanFocus = true;
		this.vpaned3.Name = "vpaned3";
		this.vpaned3.Position = 10;
		// Container child vpaned3.Gtk.Paned+PanedChild
		this.img_configBG = new global::Gtk.Image ();
		this.img_configBG.Name = "img_configBG";
		this.vpaned3.Add (this.img_configBG);
		this.GtkAlignment11.Add (this.vpaned3);
		this.fra_ConfigFrame.Add (this.GtkAlignment11);
		this.hbConfigFrame.Add (this.fra_ConfigFrame);
		global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbConfigFrame [this.fra_ConfigFrame]));
		w40.Position = 1;
		this.nbFrames.Add (this.hbConfigFrame);
		global::Gtk.Notebook.NotebookChild w41 = ((global::Gtk.Notebook.NotebookChild)(this.nbFrames [this.hbConfigFrame]));
		w41.Position = 1;
		// Notebook tab
		this.lbl_nbConfig = new global::Gtk.Label ();
		this.lbl_nbConfig.Name = "lbl_nbConfig";
		this.lbl_nbConfig.LabelProp = global::Mono.Unix.Catalog.GetString ("Config");
		this.nbFrames.SetTabLabel (this.hbConfigFrame, this.lbl_nbConfig);
		this.lbl_nbConfig.ShowAll ();
		// Container child nbFrames.Gtk.Notebook+NotebookChild
		this.bhServerSettings = new global::Gtk.HBox ();
		this.bhServerSettings.Name = "bhServerSettings";
		this.bhServerSettings.Spacing = 6;
		this.bhServerSettings.BorderWidth = ((uint)(3));
		// Container child bhServerSettings.Gtk.Box+BoxChild
		this.fraInstallationButtons = new global::Gtk.Frame ();
		this.fraInstallationButtons.Name = "fraInstallationButtons";
		this.fraInstallationButtons.ShadowType = ((global::Gtk.ShadowType)(4));
		this.fraInstallationButtons.BorderWidth = ((uint)(3));
		// Container child fraInstallationButtons.Gtk.Container+ContainerChild
		this.GtkAlignment29 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment29.Name = "GtkAlignment29";
		// Container child GtkAlignment29.Gtk.Container+ContainerChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		this.vbox5.BorderWidth = ((uint)(3));
		// Container child vbox5.Gtk.Box+BoxChild
		this.btnServerSettingsBack = new global::Gtk.Button ();
		this.btnServerSettingsBack.CanFocus = true;
		this.btnServerSettingsBack.Name = "btnServerSettingsBack";
		this.btnServerSettingsBack.UseUnderline = true;
		this.btnServerSettingsBack.Relief = ((global::Gtk.ReliefStyle)(2));
		global::Gtk.Image w42 = new global::Gtk.Image ();
		w42.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("SubZeroViewer2.res.buttons.back_blue.png");
		this.btnServerSettingsBack.Image = w42;
		this.vbox5.Add (this.btnServerSettingsBack);
		global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.btnServerSettingsBack]));
		w43.Position = 0;
		w43.Expand = false;
		w43.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.btnServerSettingsSave = new global::Gtk.Button ();
		this.btnServerSettingsSave.CanFocus = true;
		this.btnServerSettingsSave.Name = "btnServerSettingsSave";
		this.btnServerSettingsSave.UseUnderline = true;
		this.btnServerSettingsSave.Relief = ((global::Gtk.ReliefStyle)(2));
		global::Gtk.Image w44 = new global::Gtk.Image ();
		w44.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("SubZeroViewer2.res.buttons.save_blue.png");
		this.btnServerSettingsSave.Image = w44;
		this.vbox5.Add (this.btnServerSettingsSave);
		global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.btnServerSettingsSave]));
		w45.Position = 1;
		w45.Expand = false;
		w45.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.vpaned4 = new global::Gtk.VPaned ();
		this.vpaned4.CanFocus = true;
		this.vpaned4.Name = "vpaned4";
		this.vpaned4.Position = 1;
		this.vbox5.Add (this.vpaned4);
		global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.vpaned4]));
		w46.Position = 3;
		// Container child vbox5.Gtk.Box+BoxChild
		this.btnServerSettingsHome = new global::Gtk.Button ();
		this.btnServerSettingsHome.CanFocus = true;
		this.btnServerSettingsHome.Name = "btnServerSettingsHome";
		this.btnServerSettingsHome.UseUnderline = true;
		this.btnServerSettingsHome.Relief = ((global::Gtk.ReliefStyle)(2));
		global::Gtk.Image w47 = new global::Gtk.Image ();
		w47.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("SubZeroViewer2.res.buttons.home_blue.png");
		this.btnServerSettingsHome.Image = w47;
		this.vbox5.Add (this.btnServerSettingsHome);
		global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.btnServerSettingsHome]));
		w48.Position = 4;
		w48.Expand = false;
		w48.Fill = false;
		this.GtkAlignment29.Add (this.vbox5);
		this.fraInstallationButtons.Add (this.GtkAlignment29);
		this.bhServerSettings.Add (this.fraInstallationButtons);
		global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.bhServerSettings [this.fraInstallationButtons]));
		w51.Position = 0;
		w51.Expand = false;
		w51.Fill = false;
		// Container child bhServerSettings.Gtk.Box+BoxChild
		this.frame2 = new global::Gtk.Frame ();
		this.frame2.Name = "frame2";
		this.frame2.ShadowType = ((global::Gtk.ShadowType)(4));
		this.frame2.BorderWidth = ((uint)(3));
		// Container child frame2.Gtk.Container+ContainerChild
		this.GtkAlignment36 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment36.Name = "GtkAlignment36";
		// Container child GtkAlignment36.Gtk.Container+ContainerChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.fraSettings = new global::Gtk.Frame ();
		this.fraSettings.Name = "fraSettings";
		this.fraSettings.ShadowType = ((global::Gtk.ShadowType)(4));
		// Container child fraSettings.Gtk.Container+ContainerChild
		this.GtkAlignment37 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment37.Name = "GtkAlignment37";
		this.GtkAlignment37.LeftPadding = ((uint)(3));
		this.GtkAlignment37.TopPadding = ((uint)(5));
		this.GtkAlignment37.RightPadding = ((uint)(5));
		// Container child GtkAlignment37.Gtk.Container+ContainerChild
		this.vbox6 = new global::Gtk.VBox ();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox ();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.label12 = new global::Gtk.Label ();
		this.label12.Name = "label12";
		this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Friendly Name");
		this.hbox8.Add (this.label12);
		global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.label12]));
		w52.Position = 0;
		w52.Expand = false;
		w52.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.entFriendlyName = new global::Gtk.Entry ();
		this.entFriendlyName.CanFocus = true;
		this.entFriendlyName.Name = "entFriendlyName";
		this.entFriendlyName.IsEditable = true;
		this.entFriendlyName.InvisibleChar = '●';
		this.hbox8.Add (this.entFriendlyName);
		global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.entFriendlyName]));
		w53.Position = 1;
		this.vbox6.Add (this.hbox8);
		global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox8]));
		w54.Position = 0;
		w54.Expand = false;
		w54.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Protocol");
		this.hbox3.Add (this.label3);
		global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label3]));
		w55.Position = 0;
		w55.Expand = false;
		w55.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.cboProtocol = global::Gtk.ComboBoxEntry.NewText ();
		this.cboProtocol.Name = "cboProtocol";
		this.hbox3.Add (this.cboProtocol);
		global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.cboProtocol]));
		w56.Position = 1;
		w56.Expand = false;
		w56.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.entPort = new global::Gtk.Entry ();
		this.entPort.CanFocus = true;
		this.entPort.Name = "entPort";
		this.entPort.IsEditable = true;
		this.entPort.InvisibleChar = '●';
		this.hbox3.Add (this.entPort);
		global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.entPort]));
		w57.PackType = ((global::Gtk.PackType)(1));
		w57.Position = 2;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.Xalign = 1F;
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Port      ");
		this.hbox3.Add (this.label4);
		global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label4]));
		w58.PackType = ((global::Gtk.PackType)(1));
		w58.Position = 3;
		w58.Expand = false;
		w58.Fill = false;
		this.vbox6.Add (this.hbox3);
		global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox3]));
		w59.Position = 1;
		w59.Expand = false;
		w59.Fill = false;
		w59.Padding = ((uint)(3));
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Server Addr");
		this.hbox4.Add (this.label2);
		global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label2]));
		w60.Position = 0;
		w60.Expand = false;
		w60.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.entServer = new global::Gtk.Entry ();
		this.entServer.CanFocus = true;
		this.entServer.Name = "entServer";
		this.entServer.IsEditable = true;
		this.entServer.InvisibleChar = '●';
		this.hbox4.Add (this.entServer);
		global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.entServer]));
		w61.Position = 1;
		this.vbox6.Add (this.hbox4);
		global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox4]));
		w62.Position = 2;
		w62.Expand = false;
		w62.Fill = false;
		w62.Padding = ((uint)(3));
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Base Dir");
		this.hbox5.Add (this.label5);
		global::Gtk.Box.BoxChild w63 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label5]));
		w63.Position = 0;
		w63.Expand = false;
		w63.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.entBaseDir = new global::Gtk.Entry ();
		this.entBaseDir.CanFocus = true;
		this.entBaseDir.Name = "entBaseDir";
		this.entBaseDir.IsEditable = true;
		this.entBaseDir.InvisibleChar = '●';
		this.hbox5.Add (this.entBaseDir);
		global::Gtk.Box.BoxChild w64 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.entBaseDir]));
		w64.PackType = ((global::Gtk.PackType)(1));
		w64.Position = 1;
		this.vbox6.Add (this.hbox5);
		global::Gtk.Box.BoxChild w65 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox5]));
		w65.Position = 3;
		w65.Expand = false;
		w65.Fill = false;
		w65.Padding = ((uint)(3));
		// Container child vbox6.Gtk.Box+BoxChild
		this.vbox7 = new global::Gtk.VBox ();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.cbAuth = new global::Gtk.CheckButton ();
		this.cbAuth.CanFocus = true;
		this.cbAuth.Events = ((global::Gdk.EventMask)(65536));
		this.cbAuth.Name = "cbAuth";
		this.cbAuth.Label = global::Mono.Unix.Catalog.GetString ("Auhtentication Required");
		this.cbAuth.DrawIndicator = true;
		this.cbAuth.UseUnderline = true;
		this.vbox7.Add (this.cbAuth);
		global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.cbAuth]));
		w66.Position = 0;
		w66.Expand = false;
		w66.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.fraAuth = new global::Gtk.Frame ();
		this.fraAuth.Name = "fraAuth";
		this.fraAuth.ShadowType = ((global::Gtk.ShadowType)(4));
		this.fraAuth.BorderWidth = ((uint)(5));
		// Container child fraAuth.Gtk.Container+ContainerChild
		this.GtkAlignment41 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment41.Name = "GtkAlignment41";
		this.GtkAlignment41.LeftPadding = ((uint)(12));
		this.GtkAlignment41.TopPadding = ((uint)(3));
		this.GtkAlignment41.RightPadding = ((uint)(3));
		this.GtkAlignment41.BottomPadding = ((uint)(3));
		this.GtkAlignment41.BorderWidth = ((uint)(5));
		// Container child GtkAlignment41.Gtk.Container+ContainerChild
		this.vbox8 = new global::Gtk.VBox ();
		this.vbox8.Name = "vbox8";
		this.vbox8.Spacing = 6;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.label41 = new global::Gtk.Label ();
		this.label41.Name = "label41";
		this.label41.LabelProp = global::Mono.Unix.Catalog.GetString ("User Name");
		this.hbox6.Add (this.label41);
		global::Gtk.Box.BoxChild w67 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label41]));
		w67.Position = 0;
		w67.Expand = false;
		w67.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.entUname = new global::Gtk.Entry ();
		this.entUname.CanFocus = true;
		this.entUname.Name = "entUname";
		this.entUname.IsEditable = true;
		this.entUname.InvisibleChar = '●';
		this.hbox6.Add (this.entUname);
		global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.entUname]));
		w68.Position = 1;
		this.vbox8.Add (this.hbox6);
		global::Gtk.Box.BoxChild w69 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox6]));
		w69.Position = 0;
		w69.Expand = false;
		w69.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox ();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.label51 = new global::Gtk.Label ();
		this.label51.Name = "label51";
		this.label51.LabelProp = global::Mono.Unix.Catalog.GetString ("Password  ");
		this.hbox7.Add (this.label51);
		global::Gtk.Box.BoxChild w70 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.label51]));
		w70.Position = 0;
		w70.Expand = false;
		w70.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.entPword = new global::Gtk.Entry ();
		this.entPword.CanFocus = true;
		this.entPword.Name = "entPword";
		this.entPword.IsEditable = true;
		this.entPword.Visibility = false;
		this.entPword.InvisibleChar = '●';
		this.hbox7.Add (this.entPword);
		global::Gtk.Box.BoxChild w71 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.entPword]));
		w71.Position = 1;
		this.vbox8.Add (this.hbox7);
		global::Gtk.Box.BoxChild w72 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox7]));
		w72.Position = 1;
		w72.Expand = false;
		w72.Fill = false;
		this.GtkAlignment41.Add (this.vbox8);
		this.fraAuth.Add (this.GtkAlignment41);
		this.GtkLabel29 = new global::Gtk.Label ();
		this.GtkLabel29.Name = "GtkLabel29";
		this.GtkLabel29.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Authentication</b>");
		this.GtkLabel29.UseMarkup = true;
		this.fraAuth.LabelWidget = this.GtkLabel29;
		this.vbox7.Add (this.fraAuth);
		global::Gtk.Box.BoxChild w75 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.fraAuth]));
		w75.Position = 1;
		w75.Expand = false;
		w75.Fill = false;
		this.vbox6.Add (this.vbox7);
		global::Gtk.Box.BoxChild w76 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.vbox7]));
		w76.Position = 4;
		w76.Expand = false;
		w76.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.vpaned5 = new global::Gtk.VPaned ();
		this.vpaned5.CanFocus = true;
		this.vpaned5.Name = "vpaned5";
		this.vpaned5.Position = 1;
		this.vbox6.Add (this.vpaned5);
		global::Gtk.Box.BoxChild w77 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.vpaned5]));
		w77.PackType = ((global::Gtk.PackType)(1));
		w77.Position = 5;
		this.GtkAlignment37.Add (this.vbox6);
		this.fraSettings.Add (this.GtkAlignment37);
		this.hbox2.Add (this.fraSettings);
		global::Gtk.Box.BoxChild w80 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.fraSettings]));
		w80.Position = 0;
		w80.Padding = ((uint)(3));
		this.GtkAlignment36.Add (this.hbox2);
		this.frame2.Add (this.GtkAlignment36);
		this.bhServerSettings.Add (this.frame2);
		global::Gtk.Box.BoxChild w83 = ((global::Gtk.Box.BoxChild)(this.bhServerSettings [this.frame2]));
		w83.Position = 1;
		this.nbFrames.Add (this.bhServerSettings);
		global::Gtk.Notebook.NotebookChild w84 = ((global::Gtk.Notebook.NotebookChild)(this.nbFrames [this.bhServerSettings]));
		w84.Position = 2;
		// Notebook tab
		this.lbl_nbServerSettings = new global::Gtk.Label ();
		this.lbl_nbServerSettings.Name = "lbl_nbServerSettings";
		this.lbl_nbServerSettings.LabelProp = global::Mono.Unix.Catalog.GetString ("ServerSettings");
		this.nbFrames.SetTabLabel (this.bhServerSettings, this.lbl_nbServerSettings);
		this.lbl_nbServerSettings.ShowAll ();
		// Container child nbFrames.Gtk.Notebook+NotebookChild
		this.hbServerBrowser = new global::Gtk.HBox ();
		this.hbServerBrowser.Name = "hbServerBrowser";
		this.hbServerBrowser.Spacing = 6;
		this.hbServerBrowser.BorderWidth = ((uint)(3));
		// Container child hbServerBrowser.Gtk.Box+BoxChild
		this.frame3 = new global::Gtk.Frame ();
		this.frame3.Name = "frame3";
		this.frame3.ShadowType = ((global::Gtk.ShadowType)(4));
		this.frame3.BorderWidth = ((uint)(3));
		// Container child frame3.Gtk.Container+ContainerChild
		this.GtkAlignment19 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment19.Name = "GtkAlignment19";
		this.GtkAlignment19.BorderWidth = ((uint)(3));
		// Container child GtkAlignment19.Gtk.Container+ContainerChild
		this.vbox9 = new global::Gtk.VBox ();
		this.vbox9.Name = "vbox9";
		this.vbox9.Spacing = 6;
		// Container child vbox9.Gtk.Box+BoxChild
		this.btnServerBrowserBack = new global::Gtk.Button ();
		this.btnServerBrowserBack.CanFocus = true;
		this.btnServerBrowserBack.Name = "btnServerBrowserBack";
		this.btnServerBrowserBack.UseUnderline = true;
		this.btnServerBrowserBack.Relief = ((global::Gtk.ReliefStyle)(2));
		global::Gtk.Image w85 = new global::Gtk.Image ();
		w85.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("SubZeroViewer2.res.buttons.back_blue.png");
		this.btnServerBrowserBack.Image = w85;
		this.vbox9.Add (this.btnServerBrowserBack);
		global::Gtk.Box.BoxChild w86 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.btnServerBrowserBack]));
		w86.Position = 0;
		w86.Expand = false;
		w86.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.vpaned6 = new global::Gtk.VPaned ();
		this.vpaned6.CanFocus = true;
		this.vpaned6.Name = "vpaned6";
		this.vpaned6.Position = 1;
		this.vbox9.Add (this.vpaned6);
		global::Gtk.Box.BoxChild w87 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.vpaned6]));
		w87.Position = 1;
		// Container child vbox9.Gtk.Box+BoxChild
		this.btnServerBrowserHome = new global::Gtk.Button ();
		this.btnServerBrowserHome.CanFocus = true;
		this.btnServerBrowserHome.Name = "btnServerBrowserHome";
		this.btnServerBrowserHome.UseUnderline = true;
		this.btnServerBrowserHome.Relief = ((global::Gtk.ReliefStyle)(2));
		global::Gtk.Image w88 = new global::Gtk.Image ();
		w88.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("SubZeroViewer2.res.buttons.home_blue.png");
		this.btnServerBrowserHome.Image = w88;
		this.vbox9.Add (this.btnServerBrowserHome);
		global::Gtk.Box.BoxChild w89 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.btnServerBrowserHome]));
		w89.Position = 2;
		w89.Expand = false;
		w89.Fill = false;
		this.GtkAlignment19.Add (this.vbox9);
		this.frame3.Add (this.GtkAlignment19);
		this.hbServerBrowser.Add (this.frame3);
		global::Gtk.Box.BoxChild w92 = ((global::Gtk.Box.BoxChild)(this.hbServerBrowser [this.frame3]));
		w92.Position = 0;
		w92.Expand = false;
		w92.Fill = false;
		// Container child hbServerBrowser.Gtk.Box+BoxChild
		this.hbox13 = new global::Gtk.HBox ();
		this.hbox13.Name = "hbox13";
		this.hbox13.Spacing = 6;
		// Container child hbox13.Gtk.Box+BoxChild
		this.fraServerBrowser = new global::Gtk.Frame ();
		this.fraServerBrowser.Name = "fraServerBrowser";
		this.fraServerBrowser.ShadowType = ((global::Gtk.ShadowType)(4));
		this.fraServerBrowser.BorderWidth = ((uint)(3));
		// Container child fraServerBrowser.Gtk.Container+ContainerChild
		this.GtkAlignment40 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment40.Name = "GtkAlignment40";
		this.GtkAlignment40.LeftPadding = ((uint)(2));
		this.GtkAlignment40.TopPadding = ((uint)(2));
		this.GtkAlignment40.RightPadding = ((uint)(2));
		this.GtkAlignment40.BottomPadding = ((uint)(2));
		this.GtkAlignment40.BorderWidth = ((uint)(2));
		// Container child GtkAlignment40.Gtk.Container+ContainerChild
		this.ivServerBrowser = new global::Gtk.IconView ();
		this.ivServerBrowser.CanFocus = true;
		this.ivServerBrowser.Name = "ivServerBrowser";
		this.GtkAlignment40.Add (this.ivServerBrowser);
		this.fraServerBrowser.Add (this.GtkAlignment40);
		this.hbox13.Add (this.fraServerBrowser);
		global::Gtk.Box.BoxChild w95 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.fraServerBrowser]));
		w95.Position = 0;
		this.hbServerBrowser.Add (this.hbox13);
		global::Gtk.Box.BoxChild w96 = ((global::Gtk.Box.BoxChild)(this.hbServerBrowser [this.hbox13]));
		w96.Position = 1;
		this.nbFrames.Add (this.hbServerBrowser);
		global::Gtk.Notebook.NotebookChild w97 = ((global::Gtk.Notebook.NotebookChild)(this.nbFrames [this.hbServerBrowser]));
		w97.Position = 3;
		// Notebook tab
		this.lbl_nbServerBrowser = new global::Gtk.Label ();
		this.lbl_nbServerBrowser.Name = "lbl_nbServerBrowser";
		this.lbl_nbServerBrowser.LabelProp = global::Mono.Unix.Catalog.GetString ("ServerBrowser");
		this.nbFrames.SetTabLabel (this.hbServerBrowser, this.lbl_nbServerBrowser);
		this.lbl_nbServerBrowser.ShowAll ();
		// Container child nbFrames.Gtk.Notebook+NotebookChild
		this.hbDeviceBrowser = new global::Gtk.HBox ();
		this.hbDeviceBrowser.Name = "hbDeviceBrowser";
		this.hbDeviceBrowser.Spacing = 6;
		this.hbDeviceBrowser.BorderWidth = ((uint)(3));
		// Container child hbDeviceBrowser.Gtk.Box+BoxChild
		this.fraDeviceBrowserButtons = new global::Gtk.Frame ();
		this.fraDeviceBrowserButtons.Name = "fraDeviceBrowserButtons";
		this.fraDeviceBrowserButtons.ShadowType = ((global::Gtk.ShadowType)(4));
		this.fraDeviceBrowserButtons.BorderWidth = ((uint)(3));
		// Container child fraDeviceBrowserButtons.Gtk.Container+ContainerChild
		this.GtkAlignment34 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment34.Name = "GtkAlignment34";
		this.GtkAlignment34.BorderWidth = ((uint)(3));
		// Container child GtkAlignment34.Gtk.Container+ContainerChild
		this.vbox10 = new global::Gtk.VBox ();
		this.vbox10.Name = "vbox10";
		this.vbox10.Spacing = 6;
		// Container child vbox10.Gtk.Box+BoxChild
		this.btnDeviceBrowserBack = new global::Gtk.Button ();
		this.btnDeviceBrowserBack.CanFocus = true;
		this.btnDeviceBrowserBack.Name = "btnDeviceBrowserBack";
		this.btnDeviceBrowserBack.UseUnderline = true;
		this.btnDeviceBrowserBack.Relief = ((global::Gtk.ReliefStyle)(2));
		global::Gtk.Image w98 = new global::Gtk.Image ();
		w98.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("SubZeroViewer2.res.buttons.back_blue.png");
		this.btnDeviceBrowserBack.Image = w98;
		this.vbox10.Add (this.btnDeviceBrowserBack);
		global::Gtk.Box.BoxChild w99 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.btnDeviceBrowserBack]));
		w99.Position = 0;
		w99.Expand = false;
		w99.Fill = false;
		// Container child vbox10.Gtk.Box+BoxChild
		this.vpaned7 = new global::Gtk.VPaned ();
		this.vpaned7.CanFocus = true;
		this.vpaned7.Name = "vpaned7";
		this.vpaned7.Position = 1;
		this.vbox10.Add (this.vpaned7);
		global::Gtk.Box.BoxChild w100 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.vpaned7]));
		w100.Position = 1;
		// Container child vbox10.Gtk.Box+BoxChild
		this.btnDeviceBrowserHome = new global::Gtk.Button ();
		this.btnDeviceBrowserHome.CanFocus = true;
		this.btnDeviceBrowserHome.Name = "btnDeviceBrowserHome";
		this.btnDeviceBrowserHome.UseUnderline = true;
		this.btnDeviceBrowserHome.Relief = ((global::Gtk.ReliefStyle)(2));
		global::Gtk.Image w101 = new global::Gtk.Image ();
		w101.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("SubZeroViewer2.res.buttons.home_blue.png");
		this.btnDeviceBrowserHome.Image = w101;
		this.vbox10.Add (this.btnDeviceBrowserHome);
		global::Gtk.Box.BoxChild w102 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.btnDeviceBrowserHome]));
		w102.Position = 2;
		w102.Expand = false;
		w102.Fill = false;
		this.GtkAlignment34.Add (this.vbox10);
		this.fraDeviceBrowserButtons.Add (this.GtkAlignment34);
		this.hbDeviceBrowser.Add (this.fraDeviceBrowserButtons);
		global::Gtk.Box.BoxChild w105 = ((global::Gtk.Box.BoxChild)(this.hbDeviceBrowser [this.fraDeviceBrowserButtons]));
		w105.Position = 0;
		w105.Expand = false;
		w105.Fill = false;
		// Container child hbDeviceBrowser.Gtk.Box+BoxChild
		this.hbox10 = new global::Gtk.HBox ();
		this.hbox10.Name = "hbox10";
		this.hbox10.Spacing = 6;
		// Container child hbox10.Gtk.Box+BoxChild
		this.fraDeviceBrowser = new global::Gtk.Frame ();
		this.fraDeviceBrowser.Name = "fraDeviceBrowser";
		this.fraDeviceBrowser.ShadowType = ((global::Gtk.ShadowType)(2));
		this.fraDeviceBrowser.BorderWidth = ((uint)(4));
		// Container child fraDeviceBrowser.Gtk.Container+ContainerChild
		this.GtkAlignment39 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment39.Name = "GtkAlignment39";
		this.GtkAlignment39.LeftPadding = ((uint)(2));
		this.GtkAlignment39.TopPadding = ((uint)(2));
		this.GtkAlignment39.RightPadding = ((uint)(2));
		this.GtkAlignment39.BottomPadding = ((uint)(2));
		this.GtkAlignment39.BorderWidth = ((uint)(2));
		// Container child GtkAlignment39.Gtk.Container+ContainerChild
		this.ivDeviceBrowser = new global::Gtk.IconView ();
		this.ivDeviceBrowser.CanFocus = true;
		this.ivDeviceBrowser.Name = "ivDeviceBrowser";
		this.GtkAlignment39.Add (this.ivDeviceBrowser);
		this.fraDeviceBrowser.Add (this.GtkAlignment39);
		this.hbox10.Add (this.fraDeviceBrowser);
		global::Gtk.Box.BoxChild w108 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.fraDeviceBrowser]));
		w108.Position = 0;
		this.hbDeviceBrowser.Add (this.hbox10);
		global::Gtk.Box.BoxChild w109 = ((global::Gtk.Box.BoxChild)(this.hbDeviceBrowser [this.hbox10]));
		w109.PackType = ((global::Gtk.PackType)(1));
		w109.Position = 1;
		this.nbFrames.Add (this.hbDeviceBrowser);
		global::Gtk.Notebook.NotebookChild w110 = ((global::Gtk.Notebook.NotebookChild)(this.nbFrames [this.hbDeviceBrowser]));
		w110.Position = 4;
		// Notebook tab
		this.lbl_nbDeviceBrowser = new global::Gtk.Label ();
		this.lbl_nbDeviceBrowser.Name = "lbl_nbDeviceBrowser";
		this.lbl_nbDeviceBrowser.LabelProp = global::Mono.Unix.Catalog.GetString ("DeviceBrowser");
		this.nbFrames.SetTabLabel (this.hbDeviceBrowser, this.lbl_nbDeviceBrowser);
		this.lbl_nbDeviceBrowser.ShowAll ();
		// Container child nbFrames.Gtk.Notebook+NotebookChild
		this.hbDeviceSettings = new global::Gtk.HBox ();
		this.hbDeviceSettings.Name = "hbDeviceSettings";
		this.hbDeviceSettings.Spacing = 6;
		this.hbDeviceSettings.BorderWidth = ((uint)(3));
		// Container child hbDeviceSettings.Gtk.Box+BoxChild
		this.frame4 = new global::Gtk.Frame ();
		this.frame4.Name = "frame4";
		this.frame4.ShadowType = ((global::Gtk.ShadowType)(4));
		this.frame4.BorderWidth = ((uint)(3));
		// Container child frame4.Gtk.Container+ContainerChild
		this.GtkAlignment22 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment22.Name = "GtkAlignment22";
		// Container child GtkAlignment22.Gtk.Container+ContainerChild
		this.vbox11 = new global::Gtk.VBox ();
		this.vbox11.Name = "vbox11";
		this.vbox11.Spacing = 6;
		this.vbox11.BorderWidth = ((uint)(3));
		// Container child vbox11.Gtk.Box+BoxChild
		this.btnDeviceSettingsBack = new global::Gtk.Button ();
		this.btnDeviceSettingsBack.CanFocus = true;
		this.btnDeviceSettingsBack.Name = "btnDeviceSettingsBack";
		this.btnDeviceSettingsBack.UseUnderline = true;
		this.btnDeviceSettingsBack.Relief = ((global::Gtk.ReliefStyle)(2));
		global::Gtk.Image w111 = new global::Gtk.Image ();
		w111.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("SubZeroViewer2.res.buttons.back_blue.png");
		this.btnDeviceSettingsBack.Image = w111;
		this.vbox11.Add (this.btnDeviceSettingsBack);
		global::Gtk.Box.BoxChild w112 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.btnDeviceSettingsBack]));
		w112.Position = 0;
		w112.Expand = false;
		w112.Fill = false;
		// Container child vbox11.Gtk.Box+BoxChild
		this.btnDeviceSettingsSave = new global::Gtk.Button ();
		this.btnDeviceSettingsSave.CanFocus = true;
		this.btnDeviceSettingsSave.Name = "btnDeviceSettingsSave";
		this.btnDeviceSettingsSave.UseUnderline = true;
		this.btnDeviceSettingsSave.Relief = ((global::Gtk.ReliefStyle)(2));
		global::Gtk.Image w113 = new global::Gtk.Image ();
		w113.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("SubZeroViewer2.res.buttons.save_blue.png");
		this.btnDeviceSettingsSave.Image = w113;
		this.vbox11.Add (this.btnDeviceSettingsSave);
		global::Gtk.Box.BoxChild w114 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.btnDeviceSettingsSave]));
		w114.Position = 1;
		w114.Expand = false;
		w114.Fill = false;
		// Container child vbox11.Gtk.Box+BoxChild
		this.vpaned8 = new global::Gtk.VPaned ();
		this.vpaned8.CanFocus = true;
		this.vpaned8.Name = "vpaned8";
		this.vpaned8.Position = 1;
		this.vbox11.Add (this.vpaned8);
		global::Gtk.Box.BoxChild w115 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.vpaned8]));
		w115.Position = 3;
		// Container child vbox11.Gtk.Box+BoxChild
		this.btnDeviceSettingsHome = new global::Gtk.Button ();
		this.btnDeviceSettingsHome.CanFocus = true;
		this.btnDeviceSettingsHome.Name = "btnDeviceSettingsHome";
		this.btnDeviceSettingsHome.UseUnderline = true;
		this.btnDeviceSettingsHome.Relief = ((global::Gtk.ReliefStyle)(2));
		global::Gtk.Image w116 = new global::Gtk.Image ();
		w116.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("SubZeroViewer2.res.buttons.home_blue.png");
		this.btnDeviceSettingsHome.Image = w116;
		this.vbox11.Add (this.btnDeviceSettingsHome);
		global::Gtk.Box.BoxChild w117 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.btnDeviceSettingsHome]));
		w117.Position = 4;
		w117.Expand = false;
		w117.Fill = false;
		this.GtkAlignment22.Add (this.vbox11);
		this.frame4.Add (this.GtkAlignment22);
		this.hbDeviceSettings.Add (this.frame4);
		global::Gtk.Box.BoxChild w120 = ((global::Gtk.Box.BoxChild)(this.hbDeviceSettings [this.frame4]));
		w120.Position = 0;
		w120.Expand = false;
		w120.Fill = false;
		// Container child hbDeviceSettings.Gtk.Box+BoxChild
		this.vbox12 = new global::Gtk.VBox ();
		this.vbox12.Name = "vbox12";
		this.vbox12.Spacing = 6;
		// Container child vbox12.Gtk.Box+BoxChild
		this.frame11 = new global::Gtk.Frame ();
		this.frame11.Name = "frame11";
		this.frame11.ShadowType = ((global::Gtk.ShadowType)(4));
		this.frame11.BorderWidth = ((uint)(5));
		// Container child frame11.Gtk.Container+ContainerChild
		this.GtkAlignment26 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment26.Name = "GtkAlignment26";
		this.GtkAlignment26.LeftPadding = ((uint)(12));
		// Container child GtkAlignment26.Gtk.Container+ContainerChild
		this.vbox13 = new global::Gtk.VBox ();
		this.vbox13.Name = "vbox13";
		this.vbox13.Spacing = 6;
		this.vbox13.BorderWidth = ((uint)(5));
		// Container child vbox13.Gtk.Box+BoxChild
		this.hbox15 = new global::Gtk.HBox ();
		this.hbox15.Name = "hbox15";
		this.hbox15.Spacing = 6;
		// Container child hbox15.Gtk.Box+BoxChild
		this.label9 = new global::Gtk.Label ();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Device ID");
		this.hbox15.Add (this.label9);
		global::Gtk.Box.BoxChild w121 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.label9]));
		w121.Position = 0;
		w121.Expand = false;
		w121.Fill = false;
		// Container child hbox15.Gtk.Box+BoxChild
		this.entDeviceID = new global::Gtk.Entry ();
		this.entDeviceID.CanFocus = true;
		this.entDeviceID.Name = "entDeviceID";
		this.entDeviceID.IsEditable = true;
		this.entDeviceID.InvisibleChar = '●';
		this.hbox15.Add (this.entDeviceID);
		global::Gtk.Box.BoxChild w122 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.entDeviceID]));
		w122.Position = 1;
		this.vbox13.Add (this.hbox15);
		global::Gtk.Box.BoxChild w123 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.hbox15]));
		w123.Position = 0;
		w123.Expand = false;
		w123.Fill = false;
		// Container child vbox13.Gtk.Box+BoxChild
		this.hbox16 = new global::Gtk.HBox ();
		this.hbox16.Name = "hbox16";
		this.hbox16.Spacing = 6;
		// Container child hbox16.Gtk.Box+BoxChild
		this.label10 = new global::Gtk.Label ();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Description");
		this.hbox16.Add (this.label10);
		global::Gtk.Box.BoxChild w124 = ((global::Gtk.Box.BoxChild)(this.hbox16 [this.label10]));
		w124.Position = 0;
		w124.Expand = false;
		w124.Fill = false;
		// Container child hbox16.Gtk.Box+BoxChild
		this.entDeviceDescription = new global::Gtk.Entry ();
		this.entDeviceDescription.CanFocus = true;
		this.entDeviceDescription.Name = "entDeviceDescription";
		this.entDeviceDescription.IsEditable = true;
		this.entDeviceDescription.InvisibleChar = '●';
		this.hbox16.Add (this.entDeviceDescription);
		global::Gtk.Box.BoxChild w125 = ((global::Gtk.Box.BoxChild)(this.hbox16 [this.entDeviceDescription]));
		w125.Position = 1;
		this.vbox13.Add (this.hbox16);
		global::Gtk.Box.BoxChild w126 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.hbox16]));
		w126.Position = 1;
		w126.Expand = false;
		w126.Fill = false;
		// Container child vbox13.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.label11 = new global::Gtk.Label ();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Location");
		this.hbox1.Add (this.label11);
		global::Gtk.Box.BoxChild w127 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label11]));
		w127.Position = 0;
		w127.Expand = false;
		w127.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.entDeviceLocation = new global::Gtk.Entry ();
		this.entDeviceLocation.CanFocus = true;
		this.entDeviceLocation.Name = "entDeviceLocation";
		this.entDeviceLocation.IsEditable = true;
		this.entDeviceLocation.InvisibleChar = '●';
		this.hbox1.Add (this.entDeviceLocation);
		global::Gtk.Box.BoxChild w128 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.entDeviceLocation]));
		w128.Position = 1;
		this.vbox13.Add (this.hbox1);
		global::Gtk.Box.BoxChild w129 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.hbox1]));
		w129.Position = 2;
		w129.Expand = false;
		w129.Fill = false;
		// Container child vbox13.Gtk.Box+BoxChild
		this.frame14 = new global::Gtk.Frame ();
		this.frame14.Name = "frame14";
		this.frame14.ShadowType = ((global::Gtk.ShadowType)(4));
		this.frame14.BorderWidth = ((uint)(6));
		// Container child frame14.Gtk.Container+ContainerChild
		this.GtkAlignment27 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment27.Name = "GtkAlignment27";
		this.GtkAlignment27.LeftPadding = ((uint)(12));
		// Container child GtkAlignment27.Gtk.Container+ContainerChild
		this.vbox14 = new global::Gtk.VBox ();
		this.vbox14.Name = "vbox14";
		this.vbox14.Spacing = 6;
		// Container child vbox14.Gtk.Box+BoxChild
		this.hbox17 = new global::Gtk.HBox ();
		this.hbox17.Name = "hbox17";
		this.hbox17.Spacing = 6;
		// Container child hbox17.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.nvDeviceFileDescr = new global::Gtk.TreeView ();
		this.nvDeviceFileDescr.CanFocus = true;
		this.nvDeviceFileDescr.Name = "nvDeviceFileDescr";
		this.GtkScrolledWindow.Add (this.nvDeviceFileDescr);
		this.hbox17.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w131 = ((global::Gtk.Box.BoxChild)(this.hbox17 [this.GtkScrolledWindow]));
		w131.Position = 0;
		// Container child hbox17.Gtk.Box+BoxChild
		this.vbox15 = new global::Gtk.VBox ();
		this.vbox15.Name = "vbox15";
		this.vbox15.Spacing = 6;
		// Container child vbox15.Gtk.Box+BoxChild
		this.btnLogFileSensorUp = new global::Gtk.Button ();
		this.btnLogFileSensorUp.CanFocus = true;
		this.btnLogFileSensorUp.Name = "btnLogFileSensorUp";
		this.btnLogFileSensorUp.UseUnderline = true;
		this.btnLogFileSensorUp.Relief = ((global::Gtk.ReliefStyle)(2));
		global::Gtk.Image w132 = new global::Gtk.Image ();
		w132.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("SubZeroViewer2.res.buttons.up_blue.png");
		this.btnLogFileSensorUp.Image = w132;
		this.vbox15.Add (this.btnLogFileSensorUp);
		global::Gtk.Box.BoxChild w133 = ((global::Gtk.Box.BoxChild)(this.vbox15 [this.btnLogFileSensorUp]));
		w133.Position = 0;
		w133.Expand = false;
		w133.Fill = false;
		// Container child vbox15.Gtk.Box+BoxChild
		this.btnLogFileSensorDown = new global::Gtk.Button ();
		this.btnLogFileSensorDown.CanFocus = true;
		this.btnLogFileSensorDown.Name = "btnLogFileSensorDown";
		this.btnLogFileSensorDown.UseUnderline = true;
		this.btnLogFileSensorDown.Relief = ((global::Gtk.ReliefStyle)(2));
		global::Gtk.Image w134 = new global::Gtk.Image ();
		w134.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("SubZeroViewer2.res.buttons.down_blue.png");
		this.btnLogFileSensorDown.Image = w134;
		this.vbox15.Add (this.btnLogFileSensorDown);
		global::Gtk.Box.BoxChild w135 = ((global::Gtk.Box.BoxChild)(this.vbox15 [this.btnLogFileSensorDown]));
		w135.Position = 1;
		w135.Expand = false;
		w135.Fill = false;
		this.hbox17.Add (this.vbox15);
		global::Gtk.Box.BoxChild w136 = ((global::Gtk.Box.BoxChild)(this.hbox17 [this.vbox15]));
		w136.Position = 1;
		w136.Expand = false;
		w136.Fill = false;
		this.vbox14.Add (this.hbox17);
		global::Gtk.Box.BoxChild w137 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.hbox17]));
		w137.Position = 0;
		w137.Expand = false;
		w137.Fill = false;
		// Container child vbox14.Gtk.Box+BoxChild
		this.hbox20 = new global::Gtk.HBox ();
		this.hbox20.Name = "hbox20";
		this.hbox20.Spacing = 6;
		// Container child hbox20.Gtk.Box+BoxChild
		this.btnLogFileSensorAdd = new global::Gtk.Button ();
		this.btnLogFileSensorAdd.CanFocus = true;
		this.btnLogFileSensorAdd.Name = "btnLogFileSensorAdd";
		this.btnLogFileSensorAdd.UseUnderline = true;
		this.btnLogFileSensorAdd.Relief = ((global::Gtk.ReliefStyle)(2));
		global::Gtk.Image w138 = new global::Gtk.Image ();
		w138.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("SubZeroViewer2.res.buttons.add_blue.png");
		this.btnLogFileSensorAdd.Image = w138;
		this.hbox20.Add (this.btnLogFileSensorAdd);
		global::Gtk.Box.BoxChild w139 = ((global::Gtk.Box.BoxChild)(this.hbox20 [this.btnLogFileSensorAdd]));
		w139.Position = 0;
		w139.Expand = false;
		w139.Fill = false;
		// Container child hbox20.Gtk.Box+BoxChild
		this.btnLogFileSensorDelete = new global::Gtk.Button ();
		this.btnLogFileSensorDelete.CanFocus = true;
		this.btnLogFileSensorDelete.Name = "btnLogFileSensorDelete";
		this.btnLogFileSensorDelete.UseUnderline = true;
		this.btnLogFileSensorDelete.Relief = ((global::Gtk.ReliefStyle)(2));
		global::Gtk.Image w140 = new global::Gtk.Image ();
		w140.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("SubZeroViewer2.res.buttons.delete_blue.png");
		this.btnLogFileSensorDelete.Image = w140;
		this.hbox20.Add (this.btnLogFileSensorDelete);
		global::Gtk.Box.BoxChild w141 = ((global::Gtk.Box.BoxChild)(this.hbox20 [this.btnLogFileSensorDelete]));
		w141.Position = 1;
		w141.Expand = false;
		w141.Fill = false;
		// Container child hbox20.Gtk.Box+BoxChild
		this.hpaned4 = new global::Gtk.HPaned ();
		this.hpaned4.CanFocus = true;
		this.hpaned4.Name = "hpaned4";
		this.hpaned4.Position = 10;
		this.hbox20.Add (this.hpaned4);
		global::Gtk.Box.BoxChild w142 = ((global::Gtk.Box.BoxChild)(this.hbox20 [this.hpaned4]));
		w142.Position = 2;
		// Container child hbox20.Gtk.Box+BoxChild
		this.hpaned6 = new global::Gtk.HPaned ();
		this.hpaned6.CanFocus = true;
		this.hpaned6.Name = "hpaned6";
		this.hpaned6.Position = 10;
		this.hbox20.Add (this.hpaned6);
		global::Gtk.Box.BoxChild w143 = ((global::Gtk.Box.BoxChild)(this.hbox20 [this.hpaned6]));
		w143.PackType = ((global::Gtk.PackType)(1));
		w143.Position = 3;
		// Container child hbox20.Gtk.Box+BoxChild
		this.btnAddDefaultDescr = new global::Gtk.Button ();
		this.btnAddDefaultDescr.CanFocus = true;
		this.btnAddDefaultDescr.Name = "btnAddDefaultDescr";
		this.btnAddDefaultDescr.UseUnderline = true;
		this.btnAddDefaultDescr.Relief = ((global::Gtk.ReliefStyle)(2));
		global::Gtk.Image w144 = new global::Gtk.Image ();
		w144.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("SubZeroViewer2.res.buttons.add_defaults.png");
		this.btnAddDefaultDescr.Image = w144;
		this.hbox20.Add (this.btnAddDefaultDescr);
		global::Gtk.Box.BoxChild w145 = ((global::Gtk.Box.BoxChild)(this.hbox20 [this.btnAddDefaultDescr]));
		w145.PackType = ((global::Gtk.PackType)(1));
		w145.Position = 4;
		w145.Expand = false;
		w145.Fill = false;
		// Container child hbox20.Gtk.Box+BoxChild
		this.hpaned7 = new global::Gtk.HPaned ();
		this.hpaned7.CanFocus = true;
		this.hpaned7.Name = "hpaned7";
		this.hpaned7.Position = 10;
		this.hbox20.Add (this.hpaned7);
		global::Gtk.Box.BoxChild w146 = ((global::Gtk.Box.BoxChild)(this.hbox20 [this.hpaned7]));
		w146.PackType = ((global::Gtk.PackType)(1));
		w146.Position = 5;
		this.vbox14.Add (this.hbox20);
		global::Gtk.Box.BoxChild w147 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.hbox20]));
		w147.Position = 1;
		w147.Expand = false;
		w147.Fill = false;
		this.GtkAlignment27.Add (this.vbox14);
		this.frame14.Add (this.GtkAlignment27);
		this.GtkLabel26 = new global::Gtk.Label ();
		this.GtkLabel26.Name = "GtkLabel26";
		this.GtkLabel26.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Device Log File Description</b>");
		this.GtkLabel26.UseMarkup = true;
		this.frame14.LabelWidget = this.GtkLabel26;
		this.vbox13.Add (this.frame14);
		global::Gtk.Box.BoxChild w150 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.frame14]));
		w150.PackType = ((global::Gtk.PackType)(1));
		w150.Position = 3;
		w150.Expand = false;
		w150.Fill = false;
		// Container child vbox13.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox ();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.hbox12 = new global::Gtk.HBox ();
		this.hbox12.Name = "hbox12";
		this.hbox12.Spacing = 6;
		// Container child hbox12.Gtk.Box+BoxChild
		this.label14 = new global::Gtk.Label ();
		this.label14.Name = "label14";
		this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Server Subdirectory");
		this.hbox12.Add (this.label14);
		global::Gtk.Box.BoxChild w151 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.label14]));
		w151.Position = 0;
		w151.Expand = false;
		w151.Fill = false;
		// Container child hbox12.Gtk.Box+BoxChild
		this.entDeviceServerSubDir = new global::Gtk.Entry ();
		this.entDeviceServerSubDir.CanFocus = true;
		this.entDeviceServerSubDir.Name = "entDeviceServerSubDir";
		this.entDeviceServerSubDir.IsEditable = true;
		this.entDeviceServerSubDir.InvisibleChar = '●';
		this.hbox12.Add (this.entDeviceServerSubDir);
		global::Gtk.Box.BoxChild w152 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.entDeviceServerSubDir]));
		w152.Position = 1;
		// Container child hbox12.Gtk.Box+BoxChild
		this.btnSettingsBrowse = new global::Gtk.Button ();
		this.btnSettingsBrowse.CanFocus = true;
		this.btnSettingsBrowse.Name = "btnSettingsBrowse";
		this.btnSettingsBrowse.UseUnderline = true;
		this.btnSettingsBrowse.Relief = ((global::Gtk.ReliefStyle)(2));
		global::Gtk.Image w153 = new global::Gtk.Image ();
		w153.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("SubZeroViewer2.res.buttons.browse_button.png");
		this.btnSettingsBrowse.Image = w153;
		this.hbox12.Add (this.btnSettingsBrowse);
		global::Gtk.Box.BoxChild w154 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.btnSettingsBrowse]));
		w154.PackType = ((global::Gtk.PackType)(1));
		w154.Position = 2;
		w154.Expand = false;
		w154.Fill = false;
		this.hbox9.Add (this.hbox12);
		global::Gtk.Box.BoxChild w155 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.hbox12]));
		w155.Position = 0;
		this.vbox13.Add (this.hbox9);
		global::Gtk.Box.BoxChild w156 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.hbox9]));
		w156.PackType = ((global::Gtk.PackType)(1));
		w156.Position = 4;
		w156.Expand = false;
		w156.Fill = false;
		// Container child vbox13.Gtk.Box+BoxChild
		this.hbox11 = new global::Gtk.HBox ();
		this.hbox11.Name = "hbox11";
		this.hbox11.Spacing = 6;
		// Container child hbox11.Gtk.Box+BoxChild
		this.label16 = new global::Gtk.Label ();
		this.label16.Name = "label16";
		this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("Server");
		this.hbox11.Add (this.label16);
		global::Gtk.Box.BoxChild w157 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.label16]));
		w157.Position = 0;
		w157.Expand = false;
		w157.Fill = false;
		// Container child hbox11.Gtk.Box+BoxChild
		this.cboDeviceServer = global::Gtk.ComboBox.NewText ();
		this.cboDeviceServer.Name = "cboDeviceServer";
		this.hbox11.Add (this.cboDeviceServer);
		global::Gtk.Box.BoxChild w158 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.cboDeviceServer]));
		w158.PackType = ((global::Gtk.PackType)(1));
		w158.Position = 1;
		this.vbox13.Add (this.hbox11);
		global::Gtk.Box.BoxChild w159 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.hbox11]));
		w159.PackType = ((global::Gtk.PackType)(1));
		w159.Position = 5;
		w159.Expand = false;
		w159.Fill = false;
		this.GtkAlignment26.Add (this.vbox13);
		this.frame11.Add (this.GtkAlignment26);
		this.vbox12.Add (this.frame11);
		global::Gtk.Box.BoxChild w162 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.frame11]));
		w162.Position = 0;
		w162.Expand = false;
		w162.Fill = false;
		this.hbDeviceSettings.Add (this.vbox12);
		global::Gtk.Box.BoxChild w163 = ((global::Gtk.Box.BoxChild)(this.hbDeviceSettings [this.vbox12]));
		w163.Position = 1;
		this.nbFrames.Add (this.hbDeviceSettings);
		global::Gtk.Notebook.NotebookChild w164 = ((global::Gtk.Notebook.NotebookChild)(this.nbFrames [this.hbDeviceSettings]));
		w164.Position = 5;
		// Notebook tab
		this.lbl_nbDeviceSettings = new global::Gtk.Label ();
		this.lbl_nbDeviceSettings.Name = "lbl_nbDeviceSettings";
		this.lbl_nbDeviceSettings.LabelProp = global::Mono.Unix.Catalog.GetString ("DeviceSettings");
		this.nbFrames.SetTabLabel (this.hbDeviceSettings, this.lbl_nbDeviceSettings);
		this.lbl_nbDeviceSettings.ShowAll ();
		// Container child nbFrames.Gtk.Notebook+NotebookChild
		this.hbGraph = new global::Gtk.HBox ();
		this.hbGraph.Name = "hbGraph";
		this.hbGraph.Spacing = 6;
		this.hbGraph.BorderWidth = ((uint)(3));
		// Container child hbGraph.Gtk.Box+BoxChild
		this.fraButtons = new global::Gtk.Frame ();
		this.fraButtons.Name = "fraButtons";
		this.fraButtons.ShadowType = ((global::Gtk.ShadowType)(4));
		this.fraButtons.BorderWidth = ((uint)(3));
		// Container child fraButtons.Gtk.Container+ContainerChild
		this.GtkAlignment35 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment35.Name = "GtkAlignment35";
		this.GtkAlignment35.BorderWidth = ((uint)(3));
		// Container child GtkAlignment35.Gtk.Container+ContainerChild
		this.vbox17 = new global::Gtk.VBox ();
		this.vbox17.Name = "vbox17";
		this.vbox17.Spacing = 6;
		// Container child vbox17.Gtk.Box+BoxChild
		this.vbox19 = new global::Gtk.VBox ();
		this.vbox19.Name = "vbox19";
		this.vbox19.Spacing = 6;
		// Container child vbox19.Gtk.Box+BoxChild
		this.btnGraphBack = new global::Gtk.Button ();
		this.btnGraphBack.CanFocus = true;
		this.btnGraphBack.Name = "btnGraphBack";
		this.btnGraphBack.UseUnderline = true;
		this.btnGraphBack.Relief = ((global::Gtk.ReliefStyle)(2));
		global::Gtk.Image w165 = new global::Gtk.Image ();
		w165.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("SubZeroViewer2.res.buttons.back_blue.png");
		this.btnGraphBack.Image = w165;
		this.vbox19.Add (this.btnGraphBack);
		global::Gtk.Box.BoxChild w166 = ((global::Gtk.Box.BoxChild)(this.vbox19 [this.btnGraphBack]));
		w166.Position = 0;
		w166.Expand = false;
		w166.Fill = false;
		// Container child vbox19.Gtk.Box+BoxChild
		this.vpaned9 = new global::Gtk.VPaned ();
		this.vpaned9.CanFocus = true;
		this.vpaned9.Name = "vpaned9";
		this.vpaned9.Position = 1;
		this.vbox19.Add (this.vpaned9);
		global::Gtk.Box.BoxChild w167 = ((global::Gtk.Box.BoxChild)(this.vbox19 [this.vpaned9]));
		w167.Position = 1;
		this.vbox17.Add (this.vbox19);
		global::Gtk.Box.BoxChild w168 = ((global::Gtk.Box.BoxChild)(this.vbox17 [this.vbox19]));
		w168.Position = 0;
		// Container child vbox17.Gtk.Box+BoxChild
		this.btnGraphHome = new global::Gtk.Button ();
		this.btnGraphHome.CanFocus = true;
		this.btnGraphHome.Name = "btnGraphHome";
		this.btnGraphHome.UseUnderline = true;
		this.btnGraphHome.Relief = ((global::Gtk.ReliefStyle)(2));
		global::Gtk.Image w169 = new global::Gtk.Image ();
		w169.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("SubZeroViewer2.res.buttons.home_blue.png");
		this.btnGraphHome.Image = w169;
		this.vbox17.Add (this.btnGraphHome);
		global::Gtk.Box.BoxChild w170 = ((global::Gtk.Box.BoxChild)(this.vbox17 [this.btnGraphHome]));
		w170.Position = 1;
		w170.Expand = false;
		w170.Fill = false;
		this.GtkAlignment35.Add (this.vbox17);
		this.fraButtons.Add (this.GtkAlignment35);
		this.hbGraph.Add (this.fraButtons);
		global::Gtk.Box.BoxChild w173 = ((global::Gtk.Box.BoxChild)(this.hbGraph [this.fraButtons]));
		w173.Position = 0;
		w173.Expand = false;
		w173.Fill = false;
		// Container child hbGraph.Gtk.Box+BoxChild
		this.fraGraph = new global::Gtk.Frame ();
		this.fraGraph.Name = "fraGraph";
		this.fraGraph.ShadowType = ((global::Gtk.ShadowType)(4));
		// Container child fraGraph.Gtk.Container+ContainerChild
		this.GtkAlignment42 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment42.Name = "GtkAlignment42";
		// Container child GtkAlignment42.Gtk.Container+ContainerChild
		this.hbox23 = new global::Gtk.HBox ();
		this.hbox23.Name = "hbox23";
		this.hbox23.Spacing = 6;
		// Container child hbox23.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.nbGraph = new global::Gtk.Notebook ();
		this.nbGraph.CanFocus = true;
		this.nbGraph.Name = "nbGraph";
		this.nbGraph.CurrentPage = 0;
		// Container child nbGraph.Gtk.Notebook+NotebookChild
		this.swGraph = new global::Gtk.ScrolledWindow ();
		this.swGraph.CanFocus = true;
		this.swGraph.Name = "swGraph";
		this.swGraph.VscrollbarPolicy = ((global::Gtk.PolicyType)(2));
		this.swGraph.HscrollbarPolicy = ((global::Gtk.PolicyType)(0));
		this.swGraph.ShadowType = ((global::Gtk.ShadowType)(1));
		this.nbGraph.Add (this.swGraph);
		// Notebook tab
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Temperature Log");
		this.nbGraph.SetTabLabel (this.swGraph, this.label1);
		this.label1.ShowAll ();
		// Container child nbGraph.Gtk.Notebook+NotebookChild
		this.swAlarms = new global::Gtk.ScrolledWindow ();
		this.swAlarms.Name = "swAlarms";
		this.swAlarms.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child swAlarms.Gtk.Container+ContainerChild
		this.tvwAlarms = new global::Gtk.TreeView ();
		this.tvwAlarms.CanFocus = true;
		this.tvwAlarms.Name = "tvwAlarms";
		this.swAlarms.Add (this.tvwAlarms);
		this.nbGraph.Add (this.swAlarms);
		global::Gtk.Notebook.NotebookChild w176 = ((global::Gtk.Notebook.NotebookChild)(this.nbGraph [this.swAlarms]));
		w176.Position = 1;
		// Notebook tab
		this.label15 = new global::Gtk.Label ();
		this.label15.Name = "label15";
		this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("Alarms");
		this.nbGraph.SetTabLabel (this.swAlarms, this.label15);
		this.label15.ShowAll ();
		this.vbox2.Add (this.nbGraph);
		global::Gtk.Box.BoxChild w177 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.nbGraph]));
		w177.Position = 0;
		this.hbox23.Add (this.vbox2);
		global::Gtk.Box.BoxChild w178 = ((global::Gtk.Box.BoxChild)(this.hbox23 [this.vbox2]));
		w178.Position = 0;
		this.GtkAlignment42.Add (this.hbox23);
		this.fraGraph.Add (this.GtkAlignment42);
		this.lblGraph = new global::Gtk.Label ();
		this.lblGraph.Name = "lblGraph";
		this.lblGraph.UseMarkup = true;
		this.fraGraph.LabelWidget = this.lblGraph;
		this.hbGraph.Add (this.fraGraph);
		global::Gtk.Box.BoxChild w181 = ((global::Gtk.Box.BoxChild)(this.hbGraph [this.fraGraph]));
		w181.Position = 1;
		this.nbFrames.Add (this.hbGraph);
		global::Gtk.Notebook.NotebookChild w182 = ((global::Gtk.Notebook.NotebookChild)(this.nbFrames [this.hbGraph]));
		w182.Position = 6;
		// Notebook tab
		this.lbl_nbGraph = new global::Gtk.Label ();
		this.lbl_nbGraph.Name = "lbl_nbGraph";
		this.lbl_nbGraph.LabelProp = global::Mono.Unix.Catalog.GetString ("Graph");
		this.nbFrames.SetTabLabel (this.hbGraph, this.lbl_nbGraph);
		this.lbl_nbGraph.ShowAll ();
		// Container child nbFrames.Gtk.Notebook+NotebookChild
		this.hbFtpBrowser = new global::Gtk.HBox ();
		this.hbFtpBrowser.Name = "hbFtpBrowser";
		this.hbFtpBrowser.Spacing = 6;
		this.hbFtpBrowser.BorderWidth = ((uint)(3));
		// Container child hbFtpBrowser.Gtk.Box+BoxChild
		this.frame1 = new global::Gtk.Frame ();
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(4));
		this.frame1.BorderWidth = ((uint)(3));
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment43 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment43.Name = "GtkAlignment43";
		this.GtkAlignment43.BorderWidth = ((uint)(3));
		// Container child GtkAlignment43.Gtk.Container+ContainerChild
		this.vbox16 = new global::Gtk.VBox ();
		this.vbox16.Name = "vbox16";
		this.vbox16.Spacing = 6;
		// Container child vbox16.Gtk.Box+BoxChild
		this.btnFtpBack = new global::Gtk.Button ();
		this.btnFtpBack.CanFocus = true;
		this.btnFtpBack.Name = "btnFtpBack";
		this.btnFtpBack.UseUnderline = true;
		this.btnFtpBack.Relief = ((global::Gtk.ReliefStyle)(2));
		global::Gtk.Image w183 = new global::Gtk.Image ();
		w183.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("SubZeroViewer2.res.buttons.back_blue.png");
		this.btnFtpBack.Image = w183;
		this.vbox16.Add (this.btnFtpBack);
		global::Gtk.Box.BoxChild w184 = ((global::Gtk.Box.BoxChild)(this.vbox16 [this.btnFtpBack]));
		w184.Position = 0;
		w184.Expand = false;
		w184.Fill = false;
		// Container child vbox16.Gtk.Box+BoxChild
		this.vpaned12 = new global::Gtk.VPaned ();
		this.vpaned12.CanFocus = true;
		this.vpaned12.Name = "vpaned12";
		this.vpaned12.Position = 10;
		this.vbox16.Add (this.vpaned12);
		global::Gtk.Box.BoxChild w185 = ((global::Gtk.Box.BoxChild)(this.vbox16 [this.vpaned12]));
		w185.Position = 1;
		this.GtkAlignment43.Add (this.vbox16);
		this.frame1.Add (this.GtkAlignment43);
		this.hbFtpBrowser.Add (this.frame1);
		global::Gtk.Box.BoxChild w188 = ((global::Gtk.Box.BoxChild)(this.hbFtpBrowser [this.frame1]));
		w188.Position = 0;
		w188.Expand = false;
		w188.Fill = false;
		// Container child hbFtpBrowser.Gtk.Box+BoxChild
		this.frame5 = new global::Gtk.Frame ();
		this.frame5.Name = "frame5";
		this.frame5.ShadowType = ((global::Gtk.ShadowType)(4));
		this.frame5.BorderWidth = ((uint)(3));
		// Container child frame5.Gtk.Container+ContainerChild
		this.GtkAlignment45 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment45.Name = "GtkAlignment45";
		this.GtkAlignment45.LeftPadding = ((uint)(2));
		this.GtkAlignment45.TopPadding = ((uint)(2));
		this.GtkAlignment45.RightPadding = ((uint)(2));
		this.GtkAlignment45.BottomPadding = ((uint)(2));
		this.GtkAlignment45.BorderWidth = ((uint)(2));
		// Container child GtkAlignment45.Gtk.Container+ContainerChild
		this.ivFtpBrowser = new global::Gtk.IconView ();
		this.ivFtpBrowser.CanFocus = true;
		this.ivFtpBrowser.Name = "ivFtpBrowser";
		this.ivFtpBrowser.Margin = 0;
		this.GtkAlignment45.Add (this.ivFtpBrowser);
		this.frame5.Add (this.GtkAlignment45);
		this.hbFtpBrowser.Add (this.frame5);
		global::Gtk.Box.BoxChild w191 = ((global::Gtk.Box.BoxChild)(this.hbFtpBrowser [this.frame5]));
		w191.Position = 1;
		this.nbFrames.Add (this.hbFtpBrowser);
		global::Gtk.Notebook.NotebookChild w192 = ((global::Gtk.Notebook.NotebookChild)(this.nbFrames [this.hbFtpBrowser]));
		w192.Position = 7;
		// Notebook tab
		this.lbl_nbFtpBrowser = new global::Gtk.Label ();
		this.lbl_nbFtpBrowser.Name = "lbl_nbFtpBrowser";
		this.lbl_nbFtpBrowser.LabelProp = global::Mono.Unix.Catalog.GetString ("FtpBrowser");
		this.nbFrames.SetTabLabel (this.hbFtpBrowser, this.lbl_nbFtpBrowser);
		this.lbl_nbFtpBrowser.ShowAll ();
		this.vbox1.Add (this.nbFrames);
		global::Gtk.Box.BoxChild w193 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.nbFrames]));
		w193.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.sb_status = new global::Gtk.Statusbar ();
		this.sb_status.Name = "sb_status";
		this.sb_status.Spacing = 6;
		this.vbox1.Add (this.sb_status);
		global::Gtk.Box.BoxChild w194 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.sb_status]));
		w194.PackType = ((global::Gtk.PackType)(1));
		w194.Position = 2;
		w194.Expand = false;
		w194.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 1237;
		this.DefaultHeight = 1915;
		this.lbl_nbHome.Hide ();
		this.lbl_nbConfig.Hide ();
		this.btnServerSettingsSave.Hide ();
		this.fraAuth.Hide ();
		this.lbl_nbServerSettings.Hide ();
		this.lbl_nbServerBrowser.Hide ();
		this.lbl_nbDeviceBrowser.Hide ();
		this.btnDeviceSettingsSave.Hide ();
		this.lbl_nbDeviceSettings.Hide ();
		this.lbl_nbGraph.Hide ();
		this.lbl_nbFtpBrowser.Hide ();
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
